server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeefinder
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # ddl-auto: auto
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true
